<?php
	require_once(get_template_directory() . '/Inc/PostTypes/movie.php');
	require_once(get_template_directory() . '/Inc/PostTypes/serie.php');
	require_once(get_template_directory() . '/Inc/PostTypes/episode.php');
	require_once(get_template_directory() . '/Inc/PostTypes/season.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/actors.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/production.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/directors.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/writers.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/language.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/country.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/year.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/type.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/quality.php');
	require_once(get_template_directory() . '/Inc/Taxonomies/ratings.php');
	require_once(get_template_directory() . '/Inc/CusMetaBox/episode.php');
	require_once(get_template_directory() . '/Inc/CusMetaBox/season.php');
	require_once(get_template_directory() . '/Inc/MetaBox/functions.php');
	require_once(get_template_directory() . '/Inc/ThemeOptions/options-page.php');
